---

- name: Install k3s
  shell: curl -sfL https://get.k3s.io | sh -s -
  args:
    creates: /etc/rancher/k3s/k3s.yaml
  register: result
  until: "result is not failed"
  retries: 10
  delay: 10

- name: Install apt packages
  apt:
    name:
      - python3-yaml
    update_cache: yes

- name: Install helm
  shell: curl https://raw.githubusercontent.com/helm/helm/main/scripts/get-helm-3 | bash
  args:
    creates: /usr/local/bin/helm

- name: Add Prometheus Helm charts repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Deploy prometheus
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: prometheus
    chart_ref: prometheus-community/kube-prometheus-stack
    release_namespace: prometheus
    wait: True
    update_repo_cache: True
    create_namespace: True
    values:
      prometheus:
        service:
          type: LoadBalancer
        prometheusSpec:
          additionalScrapeConfigs:
            - job_name: "sandbox-{{ kypo_global_sandbox_allocation_unit_id }}"
              metrics_path: "/metrics"
              static_configs:
                - targets: "{{ groups['all'] | map('extract', hostvars, 'ansible_host') | list | product([':9100']) | map('join') | list }}"
