---

- name: Add Prometheus Helm charts repository
  kubernetes.core.helm_repository:
    name: prometheus-community
    repo_url: https://prometheus-community.github.io/helm-charts

- name: Deploy blackbox exporter
  kubernetes.core.helm:
    kubeconfig: /etc/rancher/k3s/k3s.yaml
    name: prometheus-blackbox-exporter
    chart_ref: prometheus-community/prometheus-blackbox-exporter
    release_namespace: prometheus
    wait: true
    update_repo_cache: true
    create_namespace: true
    values:
      service:
        type: LoadBalancer
      podSecurityContext:
        sysctls:
        - name: net.ipv4.ping_group_range
          value: "0 65536"
      config:
        modules:
          http_2xx:
            prober: http
            timeout: 5s
            http:
              valid_http_versions: ["HTTP/1.1", "HTTP/2.0"]
              follow_redirects: true
              preferred_ip_protocol: "ip4"
          tcp:
            prober: tcp
            tcp:
              ip_protocol_fallback: false
              preferred_ip_protocol: "ip4"
          icmp:
            prober: icmp
            icmp:
              preferred_ip_protocol: "ip4"